name: Send New-Post Notification Emails Workflow
on:
  push:
    branches:
      - main

jobs:
  notify-subscribers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run JavaScript Script
        uses: actions/github-script@v6
        with:
          script: |
            const script =
            require('../../mailing/githubActions/sendEmailsIfThereIsANewPost/sendEmailsIfThereIsANewPost.js')
            await script({github, context, core})
