name: send-new-post-notification-emails
run-name: ${{ github.actor }} is sending new-post notification emails.
on: push
  branches:
    - main
  paths:
    - src/content/posts
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
